const mongoose = require('mongoose')

const formSchema = new mongoose.Schema({
    app_fname: { type: String, required: true },
    app_mname: { type: String },
    app_lname: { type: String, required: true },
    app_dob: { type: Date, required: true },
    app_placeofbirth: { type: String, required: true },
    app_citizentype: { type: String, required: true },
    app_citizenshipno: { type: String, required: true },
    app_placeofissue: { type: String, required: true },
    app_dateofissue: { type: Date, required: true },
    add_gender: { type: String, required: true },
    add_maritalstatus: { type: String, required: true },
    add_religion: { type: String, required: true },
    add_educationlevel: { type: String, required: true },
    per_mobile: { type: String, required: true },
    per_province: { type: String, required: true },
    per_district: { type: String, required: true },
    per_municipality: { type: String, required: true },
    per_ward: { type: Number, required: true },
    per_village: { type: String, required: true },
    temp_province: { type: String },
    temp_district: { type: String },
    temp_municipality: { type: String },
    temp_ward: { type: Number },
    temp_village: { type: String },
    fat_fname: { type: String, required: true },
    fat_mname: { type: String },
    fat_lname: { type: String, required: true },
    fat_citizenshipno: { type: String, required: true },
    mot_fname: { type: String, required: true },
    mot_mname: { type: String },
    mot_lname: { type: String, required: true },
    mot_citizenshipno: { type: String, required: true },
    gfat_fname: { type: String, required: true },
    gfat_mname: { type: String },
    gfat_lname: { type: String, required: true },
    gfat_citizenshipno: { type: String, required: true },
    gmot_fname: { type: String, required: true },
    gmot_mname: { type: String },
    gmot_lname: { type: String, required: true },
    gmot_citizenshipno: { type: String, required: true },
    spou_fname: { type: String },
    spou_mname: { type: String },
    spou_lname: { type: String },
    spou_citizenshipno: { type: String },
    biometric_place: { type: String, required: true },
    biometric_date: { type: Date, required: true },
    status: {
      type: String,
      enum: ['Pre-enrollment Done', 'Biometric Done', 'To be printed', 'Printed-visit the DAO'],
      default: 'Pre-enrollment Done',
    },
  }, 
{ timestamps: true }
);

const Form = mongoose.model('Form',formSchema)
export default Form;